### ISSUE TITLE
unable to pip - "Please specify --curl-dir=/path/to/built/libcurl" error

### ISSUE THREAD

**Issue by sankionline** [upstox/upstox-python#1]
Hi., 
I am trying this on Windows PC and getting below error while installing. 

>pip install pycurl
Collecting pycurl
  Using cached pycurl-7.43.0.tar.gz
    Complete output from command python setup.py egg_info:
    **_Please specify --curl-dir=/path/to/built/libcurl_**

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 10 in C:\Users\xxxx\AppData\Local\Temp\pip-build-lya0ul6p\pycurl\

Thanks,

**Comment by svishi** [comment]
Fixed by removing the pycurl requirement

**Comment by mr-anonymus** [comment]
how can we remove the pycurl requiremnet?

**Comment by iamahmedshahh** [comment]
> how can we remove the pycurl requiremnet?

Have you got the solution yet?
