### ISSUE TITLE
modify_order order not working as before

### ISSUE THREAD

**Issue by UGHURGHURE** [upstox/upstox-python#40]
The below code was working previously but now started giving below error.
{"code":400,"status":"Bad Request","timestamp":"2021-07-09T12:49:52+05:30","message":"Can not modify this order.","error":{"name":"Error","reason":"Can not modify this order."}}

Syntax: ![image](https://user-images.githubusercontent.com/73460579/125040443-4a965280-e0b5-11eb-91dc-533e6a3a695a.png)

Here is an example: 

New_price = 100
df_temp = pd.DataFrame(u.get_order_history())
for label, row in df_temp.iterrows():
    u.modify_order(row['order_id'],
                        quantity=None,
                        order_type=None,
                        price=float(New_price),
                        trigger_price=None,
                        disclosed_quantity=None,
                        duration=None)

**Comment by qalpesh** [comment]
I am also facing the same problem.

**Comment by UGHURGHURE** [comment]
> I am also facing the same problem. It seems Upstox has changed something, API docs now doesn't show modify order.

It's working back again since today.

**Comment by qalpesh** [comment]
I just checked I am still facing the same problem, what order id did you pass for modification of order....Brokder order id or Exchange order id?

**Comment by UGHURGHURE** [comment]
> I just checked I am still facing the same problem, what order id did you pass for modification of order....Brokder order id or Exchange order id?

as i mentioned already,  Its Broker order id >>>
u.modify_order(row['order_id'],
quantity=None,
order_type=None,
price=float(New_price),
trigger_price=None,
disclosed_quantity=None,
duration=None)
