### ISSUE TITLE
Error at get_market_data_feed

### ISSUE THREAD

**Issue by harsh0520** [upstox/upstox-python#47]
```
from __future__ import print_function
import time
import upstox_client
from upstox_client.rest import ApiException
from pprint import pprint

# Configure OAuth2 access token for authorization: OAUTH2
configuration = upstox_client.Configuration()
configuration.access_token = 'YOUR_ACCESS_TOKEN'

# create an instance of the API class
api_instance = upstox_client.WebsocketApi(upstox_client.ApiClient(configuration))
api_version = 'api_version_example' # str | API Version Header

try:
    # Market Data Feed
    api_instance.get_market_data_feed(api_version)
except ApiException as e:
    print("Exception when calling WebsocketApi->get_market_data_feed: %s\n" % e)
```

NOTE : i followed the code which has been given in this GitHub repo exactly
version of library -> 2.0
python version -> 3.9.13

ERROR

URLSchemeUnknown: Not supported URL scheme wss

**Comment by Rahulzz** [comment]
Hello @harsh0520, thank you for your inquiry.

We have prepared a sample code for you to begin implementing Websockets. You can find it at the following GitHub Gist: [link to the Gist](https://gist.github.com/Rahulzz/355c714cb415a5fbefe34ac70f10f910).

We acknowledge the importance of having a direct WebSocket function, and we will consider adding this feature in future updates.

**Comment by harsh0520** [comment]
Thanks a lot @Rahulzz

**Comment by Rahulzz** [comment]
Closing this issue as the implementation details have already been shared. In addition, the repo now hosts an `/example` folder that has the WebSocket implementation samples.
