### ISSUE TITLE
ConnectionClosedError: sent 1011 (unexpected error) keepalive ping timeout; no close frame received

### ISSUE THREAD

**Issue by harsh0520** [upstox/upstox-python#49]
When I run the code for websocket, the code runs without issue for about 30min (I keep a timeout of 60 sec. so 1min data). After 30 min or at times 1hr I get this error. I checked and found that this is caused due to no response from server. Can some one kindly mention the solution for the same.

**Comment by Rahulzz** [comment]
@harsh0520 

For prompt responses to your questions and concerns, we recommend visiting our community forum at https://community.upstox.com/. Our API experts and technical team actively participate in this forum, making it the ideal place for all inquiries related to Upstox APIs.

Thank you!
