### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by trader546** [upstox/upstox-python#50]
# Configure OAuth2 access token for authorization: OAUTH2
        configuration = upstox_client.Configuration()
        configuration.access_token = 'YOUR_ACCESS_TOKEN'

what is access token ?

give an example for login.

give details about access token

**Comment by PradeepJaiswar** [comment]
We employ OAuth for both authentication and authorization purposes. You can find more information about access tokens in the context of OAuth by visiting the following link: https://auth0.com/docs/secure/tokens/access-tokens.

For details regarding authentication and login, please consult the official documentation available here: https://upstox.com/developer/api-documentation#tag/Authentication.

We are currently working on obtaining identical sections of code for different scenarios involving the API, with the goal of enhancing the speed and smoothness of our user integration.
