### ISSUE TITLE
No clear documentation

### ISSUE THREAD

**Issue by ankitagarwal** [upstox/upstox-python#52]
Hi ,

It seems almost all methods are missing detail descriptions of arguments and the same applies to parent HTTP docs on uplink site, can someone spend a few days to document all code so as to help us make more sense of examples. It is very difficult to get anything to work right now based on the limited documentation here. Do you have a starter script that fully works?

**Comment by Rahulzz** [comment]
@ankitagarwal

The script linked below provides example usages of all the methods:

https://github.com/upstox/upstox-python/blob/master/test/sanity_test.py

It's a great starting point for you.

**Comment by sarkarsayantan** [comment]
When using get_historical_candle_data api, there is no documentation of what each element in the response means.
For example, below is historical data for TCS:

code:

`
# create an instance of the API class
api_instance = upstox_client.HistoryApi()
instrument_key = 'BSE_EQ|INE467B01029' # str | 
interval = 'day' # str | 
to_date = '2023-09-13' # str | 
api_version = '2.0' # str | API Version Header

try:
    # Historical candle data
    api_response = api_instance.get_historical_candle_data(instrument_key, interval, to_date, api_version)
except ApiException as e:
    print("Exception when calling HistoryApi->get_historical_candle_data: %s\n" % e)
`
And the api_response.data.candles is something like below:

[['2023-09-12T00:00:00+05:30', 3485.05, 3589.85, 3484.05, 3580.6, 102261, 0],
 ['2023-09-11T00:00:00+05:30', 3451.15, 3484.5, 3445.1, 3479.35, 93745, 0],
 ['2023-09-08T00:00:00+05:30', 3445.05, 3463.5, 3435.1, 3443.25, 189880, 0],
 ['2023-09-07T00:00:00+05:30', 3445.95, 3462, 3423, 3455.55, 37771, 0]]

What does each element in the list refer to, no documentation for that ! Is there any reference to understanding this ?

**Comment by Rahulzz** [comment]
@sarkarsayantan

We appreciate your feedback. Soon, we will be updating our official documentation to include detailed information about the fields present in the response. Once available, this documentation will be the definitive reference for these details.

In the meantime, you can consult the response payload below, which describes the purpose of each field:

```
{
  "data": {
    "candles": [
      "2023-07-20T15:29:00+05:30",  // time
      1800.05,  // open
      1804.8,   // high
      1799.8,   // low
      1800.8,   // close
      1827,     // volume
      0         // openInterest - Applicable for FNO
    ]
  }
}
```

If you have further queries, please don't hesitate to ask.

Thank you!

**Comment by sarkarsayantan** [comment]
Thanks for the quick response @Rahulzz , really appreciate that. I want to contribute towards documentation of this, let me know if anyway I can be of help towards this. This is a great repo !

**Comment by PradeepJaiswar** [comment]
@sarkarsayantan, Thanks for being a Upstox API customer.

We will keep you informed as soon as the updated documentation becomes available. Your support is highly appreciated, and we will certainly reach out if we identify any chances for collaboration.
