### ISSUE TITLE
No data available for stocks before their stock split date

### ISSUE THREAD

**Issue by niteshbisht26** [upstox/upstox-python#54]
VBL stock was split on 15th June 2023, I can't fetch the ohlc data for VBL before 15th June.

**Comment by PradeepJaiswar** [comment]
@niteshbisht26  Could you provide more details about your request code, request payload, and response for investigation?

I suggest posting your question on the Upstox Community Forum at https://community.upstox.com/c/developer-api/15 for prompt support. Our team is highly responsive and active on this platform.
