### ISSUE TITLE
 Websocket order update

### ISSUE THREAD

**Issue by tatiyabichhoo** [upstox/upstox-python#57]
Hi Team,

Just have few question.
1. Can we connect both order update and streaming data Websocket together ?
Need to know about the order updates and want the streaming stock data i.e. ohlc/ltp date for some stocks together

2. Can we test order update websocket after the market is closed ?
Do tarting the websocket after the market is closed and then placing some orders (which will fail obviously) will show the order events like failed, placed etc. via API ?
Will it show AMO(after market order) (during trading hours and after market is closed) ?

**Comment by tatiyabichhoo** [comment]
Update: I've test the order update example.
got the access_token set it properly in code then it showed Connection established in console then I placed some order one got executed few i modified and some I cancelled.
I didn't received any order update message in console.

Is it a bug ?

**Comment by marif4444** [comment]
I'm also facing same issue.

**Comment by marif4444** [comment]
Can you guys please help? @Rahulzz @AlokGaira

**Comment by marif4444** [comment]
do we need to send the subscription message? if yes message format?

**Comment by Rahulzz** [comment]
@tatiyabichhoo 

It sounds like you've followed the necessary steps to set up and use the order update example. Typically, when an order is placed, modified, or canceled, the relevant updates should be sent to the connected WebSocket client. The example code you're referring to was functional and tested when it was compiled. I recommend trying out the process again to see if the issue persists. 

For a quicker resolution and more specific guidance, it would be beneficial to reach out to the community at [Upstox Community](https://community.upstox.com/). The community forum is a great place to seek help from other users who might have faced similar issues, as well as from experts who are familiar with the Upstox API and its intricacies. They can provide more targeted advice and solutions based on their experience.

**Comment by Rahulzz** [comment]
@marif4444 

If you're experiencing issues with your WebSocket connection, I recommend reviewing the examples provided in the Upstox Python SDK for guidance on how to correctly set up and use WebSocket connections. These examples can be a valuable resource for understanding the proper implementation and can be found at the following URL: [Upstox Python SDK Examples](https://github.com/upstox/upstox-python/tree/master/examples).

In case you continue to face issues or have specific questions that are not addressed by the examples, please don't hesitate to reach out for support on the Upstox Community forum. The community at [Upstox Community](https://community.upstox.com/) is a great place to seek assistance, where you can get help from both fellow users and experts familiar with the Upstox API. They can provide you with more targeted advice and potential solutions to your problem.
