### ISSUE TITLE
Market Depth Upto 20

### ISSUE THREAD

**Issue by rosevinod** [upstox/upstox-python#61]
It is humbly requested to provide live market feed for Market Depth up to 20

**Comment by PradeepJaiswar** [comment]
Thank you for your inquiry. We are currently considering Market Depth up to 20 in our initial discussions. However, we don't have an estimated time of arrival for this feature yet. I will be sure to follow up with you as soon as we have made further progress.

**Comment by PradeepJaiswar** [comment]
@rosevinod 

For prompt responses to your questions and concerns, we recommend visiting our community forum at https://community.upstox.com/. Our API experts and technical team actively participate in this forum, making it the ideal place for all inquiries related to Upstox APIs.

Thank you!

**Comment by rosevinod** [comment]
@PradeepJaiswar Thanks for your reply. Please make sure to provide 20 depths and total traded volume in a single API. No, other broker provide this feature. Current, many brokers are missing this feature. This is an added advantage.
