### ISSUE TITLE
Authentication not working in Native Python Library

### ISSUE THREAD

**Issue by febinmathew** [upstox/upstox-python#62]
For auth we need to call:
`api_response = api_instance.token(api_version, code=code, client_id=client_id, client_secret=client_secret, redirect_uri=redirect_uri, grant_type=grant_type)`

For this, we need the `code` parameter, which we should be getting from **authorize** function call:

`api_instance.authorize(client_id, redirect_uri, api_version, state=state, scope=scope)`

But this will always return **None**. So where are we suppose to get the `code` value? This works perfect in browser with redirection url. But not with official Python library.

**Comment by aks473** [comment]
Same here, is someone even looking at this repo and this issue.

**Comment by Rahulzz** [comment]
@febinmathew @aks473 

Please review the authorization process as outlined here: [Upstox API Authentication Documentation](https://upstox.com/developer/api-documentation/authentication). 

The authorization function, which is not synchronous, should be used in a web browser to start the OAuth flow. After this process completes, the system will redirect to the `redirect_uri` you provided during registration. You will receive a code as a request parameter upon redirection to your URI. This code must then be used with the token API to generate an `access_token`. 

For further questions, please join our active community at [Upstox Community](https://community.upstox.com/).
