### ISSUE TITLE
Is there any plan to include date time or Volume in OHLC Quotes API

### ISSUE THREAD

**Issue by princesingh** [upstox/upstox-python#64]
Currently, API response does not contain any date time or even volume.

**Comment by PradeepJaiswar** [comment]
@princesingh 

Thank you for your feedback. I'll ensure that the appropriate team receives this information for further review.

For prompt responses to your questions and concerns, we recommend visiting our community forum at https://community.upstox.com/. Our API experts and technical team actively participate in this forum, making it the ideal place for all inquiries related to Upstox APIs.

Thank you!
