### ISSUE TITLE
How to use the SDK to get a ticker symbol's OHLC ?

### ISSUE THREAD

**Issue by arsoni20** [upstox/upstox-python#74]
Hi, 

Could anyone please let me know how can i get OHLC for a ticker symbol like TATASTEEL via uplink API ?

Thanks

**Comment by KetanGupta12** [comment]
Hello @arsoni20,

To begin, you will need to locate the instrument key for the specified symbol from the [instruments file](https://upstox.com/developer/api-documentation/instruments#json-files).

Once you have the instrument key, you can call the [LTP Market Quote API](https://upstox.com/developer/api-documentation/ltp) using this key. Alternatively, if you require a continuous feed of LTP, you can connect to the [Market Feeder WebSocket](https://upstox.com/developer/api-documentation/get-market-data-feed).


Note: For a faster response and a more engaging community experience, we recommend posting your question on our [developer community](https://community.upstox.com/c/developer-api/15)

Thank you
