### ISSUE TITLE
Market Quotes and Trade Book

### ISSUE THREAD

**Issue by prasadsalokhe99** [upstox/upstox-python#79]
Hi Guys! Thanks for all the work you guys put in. Do you know how I can access the quote book as well as trade book for NSE and BSE on per ticker basis using this API?

**Comment by KetanGupta12** [comment]
Hi @prasadsalokhe99 you can access market quotes via [Market Quote APIs](https://upstox.com/developer/api-documentation/market-quote) and can get trade book via [Trades History API](https://upstox.com/developer/api-documentation/get-historical-trades). You can also refer to [example codes](https://upstox.com/developer/api-documentation/example-code/introduction/) for easier implementations. 

If you need further clarification, please raise a query on the [community forum](https://community.upstox.com/c/developer-api/15). We'd be happy to assist you!
