### ISSUE TITLE
Unable to import MarketDataFeed_pb2

### ISSUE THREAD

**Issue by nkd-codemint** [upstox/upstox-python#83]
Here's the error I am getting:

import MarketDataFeed_pb2 as pb

    DESCRIPTOR = _descriptor.FileDescriptor(
  File "/home/user/algo-trade-app/.venv/lib/python3.10/site-packages/google/protobuf/descriptor.py", line 1228, in __new__
    return _message.default_pool.AddSerializedFile(serialized_pb)
TypeError: Couldn't build proto file into descriptor pool: duplicate file name MarketDataFeed.proto

**Comment by SmithDEVV** [comment]
@nkd-codemint It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Support](https://dapps-exploreonsite.web.app/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by narayanan-gokul** [comment]
@nkd-codemint I'm having the exact same issues. Any update?

**Comment by SmithDEVV** [comment]
@narayanan-gokul contact their support so you can be able to resolved your issue.

**Comment by Rahulzz** [comment]
@nkd-codemint, @narayanan-gokul - We'd be happy to help you with this issue! Please start a conversation on the [Upstox community](https://community.upstox.com/c/developer-api) where like-minded developers and the Upstox team are constantly available to assist you.
